# Generated by Django 4.1 on 2022-11-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="disfraces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=5)),
                ("nombre", models.CharField(max_length=50)),
                ("fono", models.CharField(max_length=25)),
                ("email", models.CharField(max_length=50)),
            ],
        ),
    ]
