# Generated by Django 4.1 on 2022-11-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disfraces",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="disfraces",
            name="email",
        ),
        migrations.CreateModel(
            name="Arrendatario",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("fono", models.CharField(max_length=25)),
                (
                    "codigo_disfraz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aplicacion.disfraces",
                    ),
                ),
            ],
        ),
    ]
