# Generated by Django 4.1.3 on 2022-11-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0002_remove_disfraces_codigo_remove_disfraces_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disfraces",
            name="fono",
        ),
        migrations.AddField(
            model_name="arrendatario",
            name="descripcion",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="arrendatario",
            name="fecha_arriendo",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="arrendatario",
            name="fecha_entrega",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="disfraces",
            name="precio",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="arrendatario",
            name="codigo_disfraz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="aplicacion.disfraces",
            ),
        ),
        migrations.AlterField(
            model_name="arrendatario",
            name="fono",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="arrendatario",
            name="nombre",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="disfraces",
            name="nombre",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
