# Generated by Django 4.1.3 on 2022-12-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_disfraces_fono_arrendatario_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disfraces',
            old_name='precio',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='disfraces',
            old_name='nombre',
            new_name='Nombre_disfraz',
        ),
        migrations.AddField(
            model_name='disfraces',
            name='Accesorios',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disfraces',
            name='Para',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disfraces',
            name='Precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='disfraces',
            name='Talla',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
